# docker-compose.yml
version: '3.11'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: face_recognizer_dev
